language: cpp
compiler: gcc

script:
  - ./configure && make test

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"