# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mcneip01/uni/CI301/lodge

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mcneip01/uni/CI301/lodge

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mcneip01/uni/CI301/lodge/CMakeFiles /Users/mcneip01/uni/CI301/lodge/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mcneip01/uni/CI301/lodge/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lodge

# Build rule for target.
lodge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lodge
.PHONY : lodge

# fast build rule for target.
lodge/fast:
	$(MAKE) -f src/CMakeFiles/lodge.dir/build.make src/CMakeFiles/lodge.dir/build
.PHONY : lodge/fast

#=============================================================================
# Target rules for targets named lodge_lib

# Build rule for target.
lodge_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lodge_lib
.PHONY : lodge_lib

# fast build rule for target.
lodge_lib/fast:
	$(MAKE) -f src/CMakeFiles/lodge_lib.dir/build.make src/CMakeFiles/lodge_lib.dir/build
.PHONY : lodge_lib/fast

#=============================================================================
# Target rules for targets named lodge_tests

# Build rule for target.
lodge_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lodge_tests
.PHONY : lodge_tests

# fast build rule for target.
lodge_tests/fast:
	$(MAKE) -f test/CMakeFiles/lodge_tests.dir/build.make test/CMakeFiles/lodge_tests.dir/build
.PHONY : lodge_tests/fast

#=============================================================================
# Target rules for targets named lodge_gui

# Build rule for target.
lodge_gui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lodge_gui
.PHONY : lodge_gui

# fast build rule for target.
lodge_gui/fast:
	$(MAKE) -f gui/CMakeFiles/lodge_gui.dir/build.make gui/CMakeFiles/lodge_gui.dir/build
.PHONY : lodge_gui/fast

#=============================================================================
# Target rules for targets named lodge_gui_autogen

# Build rule for target.
lodge_gui_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lodge_gui_autogen
.PHONY : lodge_gui_autogen

# fast build rule for target.
lodge_gui_autogen/fast:
	$(MAKE) -f gui/CMakeFiles/lodge_gui_autogen.dir/build.make gui/CMakeFiles/lodge_gui_autogen.dir/build
.PHONY : lodge_gui_autogen/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lodge"
	@echo "... lodge_lib"
	@echo "... lodge_tests"
	@echo "... lodge_gui"
	@echo "... lodge_gui_autogen"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

